name: Siege_Warfare_Plugin
version: '${version}'
main: com.hashibutogarasu.siege_warfare_plugin.Siege_Warfare_Plugin
api-version: 1.18

commands:
  setteam:
    description: モードを指定してチームをセットします random：ランダム指定 custom：カスタム指定
    usage: /<command> mode
  startsiegewarfare:
    description: セットしたチームで攻城戦を開始します
    usage: /<command>